apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    environment: production
    app: app
spec:
  containers:
    - name: nginx
      image: salarmgh/app:webserver-v2
    - name: fpm
      image: salarmgh/app:fpm-v1
