apiVersion: v1
kind: Pod
metadata:
  name: mytest
  labels:
    environment: staging
    app: mytest
spec:
  containers:
    - name: nginx
      image: nginx:1.21.6
    - name: busybox
      image: busybox
      tty: true
      command: 
        - /bin/cat
