apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: percona
  serviceName: "mysql"
  replicas: 2
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: percona
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
        - name: init-mysql
          image: dockerhub.ir/busybox
          command:
            [
              "sh",
              "-c",
              'echo "[mysqld]" > /etc/my.cnf.d/server_id.cnf && echo server-id = $(echo "$(echo $HOSTNAME | cut -d- -f2) + 1" | bc) >> /etc/my.cnf.d/server_id.cnf && echo "log_bin = /var/lib/mysql/mysql-bin.log" >> /etc/my.cnf.d/server_id.cnf',
            ]
          volumeMounts:
            - mountPath: /etc/my.cnf.d/
              name: mysql-config
      containers:
        - name: percona
          image: dockerhub.ir/percona:8.0.27-18
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_DATABASE
              value: wordpress_db
            - name: MYSQL_USER
              value: wordpress_user
            - name: MYSQL_PASSWORD
              value: wordpress_pass
            - name: MYSQL_ROOT_PASSWORD
              value: root
          volumeMounts:
            - mountPath: /etc/my.cnf.d/
              name: mysql-config
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "mysql --help"]
      volumes:
        - name: mysql-config
          emptyDir: {}
