apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  completionMode: Indexed
  completions: 8
  parallelism: 2
  template:
    spec:
      containers:
      - name: pi
        image: dockerhub.ir/perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4
