kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: 5k1K8EcOjJxRdqlq04DaBjzmPsXIB0wzgLBIAApFz3Q=
      - identity: {}
