apiVersion: v1
kind: Pod
metadata:
  labels:
    run: deployer
  name: deployer
  namespace: cicd
spec:
  containers:
    - image: registry.anisa.lab/deployer
      imagePullPolicy: IfNotPresent
      name: deployer
      tty: true
      command:
        - /bin/cat
  serviceAccount: deployer
