apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health {
            lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        file /etc/coredns/anisa.lab.db anisa.lab
        forward . /etc/resolv.conf {
          prefer_udp
        }
        cache 30

        loop
        reload
        loadbalance
    }
  anisa.lab.db: |
    ; anisa.lab
    anisa.lab.            IN      SOA     sns.dns.icann.org. noc.dns.icann.org. 2015082541 7200 3600 1209600 3600
    anisa.lab.            IN      NS      b.iana-servers.net.
    anisa.lab.            IN      NS      a.iana-servers.net.
    anisa.lab.            IN      A       192.168.56.13
    registry.anisa.lab.   IN      A       192.168.56.13

    service.anisa.lab.    IN      SRV     8080 10 10 anisa.lab. 
kind: ConfigMap
metadata:
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
  name: coredns
  namespace: kube-system
