apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.21.6
      livenessProbe:
        httpGet:
          path: /foo
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 5
