apiVersion: v1
kind: Pod
metadata:
  name: pod-env
spec:
  containers:
    - name: pod-env
      image: dockerhub.ir/nginx:1.21.6
      env:
        - name: foo
          value: bar
      envFrom:
        - configMapRef:
            name: nginx-config
