apiVersion: v1
kind: Pod
metadata:
  name: pod-args
spec:
  containers:
    - name: pod-args
      image: dockerhub.ir/nginx:1.21.6
      command:
        - /usr/sbin/nginx
      args:
        - "$(params);"
      envFrom:
        - configMapRef:
            name: nginx-config
